//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeForVisit
    {
        public int Id { get; set; }
        public System.DateTime VisitTime { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Cabinet Cabinet { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
